# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('image_url', models.TextField()),
                ('rating_before', models.FloatField()),
                ('rating_after', models.FloatField()),
                ('num_news', models.IntegerField(default=0)),
                ('distributor', models.IntegerField(default=0)),
                ('num_viewers', models.IntegerField(default=0)),
            ],
        ),
    ]
