# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image_url', models.TextField()),
                ('before_grade', models.FloatField(default=5.0)),
                ('after_grade', models.FloatField(default=5.0)),
                ('movie_code', models.IntegerField(default=0)),
                ('naver_url', models.TextField()),
                ('screen_num_7', models.IntegerField(default=0)),
                ('show_num_7', models.IntegerField(default=0)),
                ('audience_num_7', models.IntegerField(default=0)),
                ('money_num_7', models.IntegerField(default=0)),
                ('distributor_effect', models.IntegerField(default=0)),
                ('actor_effect', models.IntegerField(default=0)),
                ('director_effect', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('nationality', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('audience_num', models.IntegerField(default=0)),
            ],
        ),
    ]
